
modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "Electron"
original_creator = "Aspect_Xero"
description = '''just adding some stargates variants'''


[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId="sgjourney"
type = "required"
versionRange="[0.6.40,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.moregate]]
modId = "create"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.moregate]]
modId = "ae2"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
